version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: faker
    versions:
    - "> 5.6.0"
  - dependency-name: marshmallow
    versions:
    - "> 2.19.2"
  - dependency-name: marshmallow
    versions:
    - ">= 3.2.a, < 3.3"
  - dependency-name: requests-oauthlib
    versions:
    - "> 1.1.0"
  - dependency-name: sqlalchemy
    versions:
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.3
    - 1.4.4
  - dependency-name: followthemoney
    versions:
    - 2.3.2
    - 2.4.0
    - 2.4.1
    - 2.4.3
    - 2.5.1
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.5.0
    - 2.5.1
  - dependency-name: banal
    versions:
    - 1.0.2
    - 1.0.5
    - 1.0.6
  - dependency-name: normality
    versions:
    - 2.1.2
    - 2.1.3
  - dependency-name: fingerprints
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: tabulate
    versions:
    - 0.8.9
  - dependency-name: flask-migrate
    versions:
    - 2.7.0
  - dependency-name: alembic
    versions:
    - 1.5.5
  - dependency-name: elasticsearch
    versions:
    - 7.11.0
  - dependency-name: cryptography
    versions:
    - 3.3.2
    - "3.4"
    - 3.4.2
    - 3.4.4
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: react
    versions:
    - ">= 17.0.a, < 17.1"
  - dependency-name: "@alephdata/react-ftm"
    versions:
    - 2.3.11
    - 2.3.2
    - 2.3.7
    - 2.3.9
  - dependency-name: "@blueprintjs/datetime"
    versions:
    - 3.20.5
    - 3.21.0
    - 3.21.2
    - 3.22.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@blueprintjs/icons"
    versions:
    - 3.25.0
  - dependency-name: "@blueprintjs/core"
    versions:
    - 3.40.0
  - dependency-name: "@blueprintjs/table"
    versions:
    - 3.8.23
    - 3.8.24
  - dependency-name: "@alephdata/followthemoney"
    versions:
    - 2.3.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  target-branch: develop
- package-ecosystem: docker
  directory: "/ui"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  target-branch: develop
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    time: "01:00"
  open-pull-requests-limit: 99
  target-branch: develop
