language: python
cache:
  - apt
  - pip
  - npm
python:
  - "2.7"
services:
  - postgresql
  - elasticsearch
  - rabbitmq
addons:
  postgresql: "9.4"
  apt:
    packages:
      - python-software-properties
      - libtesseract-dev
      - wkhtmltopdf
      - poppler-utils
      - libreoffice
      - djvulibre-bin
env:
  global:
    - ALEPH_TEST_SETTINGS=$TRAVIS_BUILD_DIR/test_settings.py
    - WKHTMLTOPDF_BIN=$TRAVIS_BUILD_DIR/wkhtmltox/bin/wkhtmltopdf
    - OAUTH_KEY=fake
    - OAUTH_SECRET=fake
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr-eng readpst
  - wget --quiet -O /tmp/wkhtmltox.tar.xv http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
  - tar -xf /tmp/wkhtmltox.tar.xv -C $TRAVIS_BUILD_DIR
install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -e .
  - pip install psycopg2 coveralls
  - npm install bower
  - npm install .
before_script:
  - psql -c 'create database aleph_test;' -U postgres
  - cp $TRAVIS_BUILD_DIR/test_settings.py.tmpl $TRAVIS_BUILD_DIR/test_settings.py
  - nosetests --version
  - psql --version
script:
  - make assets && nosetests --with-coverage --cover-package=aleph
after_success:
  - coveralls
