# SPDX-FileCopyrightText: 2014 2014 Emma Prest, <emma@occrp.org> et al.
#
# SPDX-License-Identifier: MIT

---
nodeGroup: "master"
masterService: "aleph-index-master"
clusterName: "aleph-index"

roles:
  master: "true"
  ingest: "false"
  data: "false"
  ml: "false"
  remote_cluster_client: "false"

replicas: 2

image: "ghcr.io/alephdata/aleph-elasticsearch"
imageTag: "3bb5dbed97cfdb9955324d11e5c623a5c5bbc410"
imagePullPolicy: "IfNotPresent"

esJavaOpts: "-Xmx1g -Xms1g"
esConfig:
  elasticsearch.yml: |
    xpack:
      graph:
        enabled: "false"
      ml:
        enabled: "false"
      security:
        enabled: "false"

resources:
  requests:
    cpu: "300m"
    memory: "1500Mi"
  limits:
    cpu: "600m"
    memory: "2000Mi"

volumeClaimTemplate:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi

antiAffinity: disable
