name: End to end tests

on:
  pull_request_target:
    types:
      - closed
    branches-ignore:
      - 'dependabot/*'
  push:
    tags:
      - '*'
    schedule:
      # Run weekly
      - cron: '30 15 * * 0'
  workflow_dispatch:

jobs:
  e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up
        run: |
          sudo sysctl -w vm.max_map_count=262144
          sudo echo "ALEPH_SECRET_KEY=batman\n" >> aleph.env
          echo "${GITHUB_REF}"
          docker --version
          docker compose --version

      - name: Build e2e image
        run: make build-e2e

      - name: Pull and start services
        run: make services-e2e

      - name: Run tests
        run: make e2e

      - name: Archive test result artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: e2e/test-results/

      - name: Dump docker logs on failure
        uses: jwalton/gh-docker-logs@v2
        if: failure()
